leftnav:
- identifier: c9378ca2-d17d-7bca-b207-8dac91cdeb2a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: c7733300-65e6-1304-5d19-52a2e568756e
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 3250f843-6e28-da99-a650-6994ebacc046
  name: Recitations
  url: /pages/recitations
  weight: 30
- identifier: d340dcdb-52b7-b0af-afd3-fef584b6f275
  name: Labs
  url: /pages/labs
  weight: 40
- identifier: fe3f3410-c1d7-3bd9-1a52-19f48db5ca44
  name: Assignments
  url: /pages/assignments
  weight: 50
